assets/js/claim.js

Fixes https://www.pivotaltracker.com/story/show/174335062

Resize .collapsible-content when error message is appended

---

assets/js/main.js
content/learn/defi-app-how-to.en.md

Update download links for change of app name

feat: updated download links

---

.dockerignore
.github/workflows/deploy.yaml
Dockerfile
assets/js/main.js
config.toml
test/Dockerfile

Github actions will deploy the following:
- en: To github pages
- zh-hans: Image deployment to alibaba cloud
- zh-hant: Image deployment to alibaba cloud

Actions Workflow for deployment to multiple region

---

.github/workflows/deploy.yaml

Update github actions to deploy to S3

---

content/en/bug-bounty.en.md

Bug bounty updates

---

content/zh-hans/_index.zh-hans.md
content/zh-hant/_index.zh-hant.md

Updated Buy DFI text on zht & zhs langs

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

Fixed release-drafter

---

content/zh-hans/downloads.zh-hans.md
content/zh-hant/downloads.zh-hant.md

- Updated saiive.live Links for zh langs

Updated saiive.live Links for zh langs

---

assets/js/main.js
content/en/downloads.en.md
content/zh-hans/downloads.zh-hans.md
content/zh-hant/downloads.zh-hant.md

Fixed download links. Isolated ajax div updates to dfc app download links only.

Fixed downloads for non dfc apps

---

layouts/airdrop-closed/single.html
layouts/airdrop-coming-soon/single.html
layouts/airdrop/single.html
layouts/article/single.html
layouts/bug-bounty/single.html
layouts/downloads/single.html
layouts/foundation/single.html
layouts/index.html
layouts/learn/single.html
layouts/partials/section-closer-look.html

Removed mailing list section for all pages

---

content/en/airdrop-6qfku6m2hp.en.md
content/en/downloads.en.md
content/zh-hans/airdrop-6qfku6m2hp.zh-hans.md
content/zh-hans/downloads.zh-hans.md
content/zh-hant/airdrop-6qfku6m2hp.zh-hant.md
content/zh-hant/downloads.zh-hant.md

Fixed fallback download links
Fixes #53

Fixed fallback download links

---

config.toml

Updated dfx link

---

assets/scss/_layout.scss

Fixed logo getting clipped on window resize

Fixed logo clipping

---

content/en/_index.en.md
content/zh-hans/_index.zh-hans.md
content/zh-hant/_index.zh-hant.md

Fixes DeFiScan link in the 2021 roadmap.
Closes #75

Fixed defiscan link

---

layouts/bug-bounty/single.html
netlify.toml

Adds `Content-Disposition` header to GPG file.

Added header for GPG key

---

src/layouts/components/Footer.tsx
src/layouts/components/Header.tsx

- Update layout to use Whale client instead of calling the URL directly

Update layout to use Whale client

---

content/en/learn/swap-and-arbitrage.en.md

Update swap-and-arbitrage.en.md Correction

---

content/en/learn/obtaining-wrapped-tokens.en.md

kind chore 
Correction (two times the same field.)

Update obtaining-wrapped-tokens.en.md Correction

---

content/en/dfi.en.md

Update dfi.en.md Corrrection

---

content/en/learn.en.md

Update learn.en.md Correction

---

content/en/learn.en.md

Removed video

---

content/en/white-paper.en.md

Update white-paper.en.md Correction of amounts for fees

---

netlify.toml
next.config.js
public/_headers
src/components/commons/PageHeader.tsx
src/components/commons/ResourceCard.tsx
src/layouts/components/BuyDFIButton.tsx
src/layouts/components/Footer.tsx
src/layouts/components/Header.tsx
src/layouts/components/LanguageDropdown.tsx
src/pages/bug-bounty/index.page.tsx
src/pages/developers/index.page.tsx
src/pages/dex/index.page.tsx
src/pages/dfi/index.page.tsx
src/pages/downloads/index.page.tsx
src/pages/ecosystem/index.page.tsx
src/pages/learn/[slug].page.tsx
src/pages/learn/index.page.tsx
src/pages/privacy-policy.page.tsx
src/pages/security.page.tsx
src/pages/white-paper.page.tsx

- CMC Widget
- Netlify Redirect
- Cod Cleanups
-

CMC Widget and added netlify redirects

---

CONTRIBUTING.md
README.md

Updated README & CONTRIBUTING

---

public/locales/en-US/layout.json
public/locales/zh-Hans/layout.json
public/locales/zh-Hant/layout.json
src/layouts/components/Footer.tsx
src/layouts/components/Header.tsx

Add blog to header and footer
Fixes: #27

Add blog to header and footer

---

src/pages/downloads/_components/FullNodeSection.tsx
src/pages/downloads/_components/LightWalletSection.tsx

Fixed download links

---

public/locales/en-US/page-bugbounty.json
public/locales/zh-Hans/page-bugbounty.json
public/locales/zh-Hant/page-bugbounty.json
src/pages/bug-bounty/_components/Hunter.tsx
src/pages/bug-bounty/index.page.tsx

- Updated bug bounty payouts
- Added new bounty hunters

Bug bounty payout updates

---

src/pages/downloads/_components/FullNodeSection.tsx

Updated dfc app wallet version

Updated dfc app wallet version

---

public/locales/en-US/page-downloads.json
public/locales/zh-Hans/page-downloads.json
public/locales/zh-Hant/page-downloads.json

Updated electrum desc with translations

Updated electrum desc with translations

---

cypress/integration/layout/footer.spec.ts
src/layouts/components/Footer.tsx

Removed ZH Telegram from social section

---

next.config.js
public/_headers

Added `*.cloudfront.net` to csp

Added cloudfront to csp

---

src/pages/dfi/_components/ExchangeSection.tsx

Fixed hoo logo

---

content/_learn/en-US/defi-app-how-to.md

chore(translations): updated defi-app-how-to.md

---

content/_learn/en-US/swap-and-arbitrage.md
content/_learn/en-US/wallet-encryption.md
cypress/integration/pages/dfi.spec.ts
public/locales/en-US/page-dfi.json
public/locales/zh-Hans/page-dfi.json
public/locales/zh-Hant/page-dfi.json
src/pages/dfi/_components/ExchangeSection.tsx

chore(fix): updated page-dfi.json

---

public/locales/en-US/page-index.json
public/locales/zh-Hans/page-index.json
public/locales/zh-Hant/page-index.json

chore(fix): updating page-index.json

---

public/locales/en-US/page-dfi.json
public/locales/zh-Hans/page-dfi.json
public/locales/zh-Hant/page-dfi.json
src/pages/dfi/_components/DistributionSection.tsx

Updated $DFI Chart

---

src/styles/globals.css

Fixed default carousel arrow from showing

Fixed default carousel arrow from showing

---

src/pages/dfi/_components/ExchangeSection.tsx

Signed-off-by: Suraj Auwal <siradjiawoual@gmail.com>
Fix Broken link to Transak Exchange
#182

Updated Transak link

---

src/layouts/components/BuyDFIButton.tsx

fixed  transak link 

---

src/pages/downloads/_components/FullNodeSection.tsx

`Downloads`: Updated app and ain versions

---

.idea/modules.xml
next.config.js
public/_headers
src/pages/downloads/_components/DynamicDownloadCard.tsx
src/pages/downloads/_components/FullNodeSection.tsx

Dynamically retrieves latest DefiChain App version for download instead of updating manually

`Downloads`: Extract the latest versions from GitHub for defichain apps downloads

---

content/white-paper/white-paper.de.md

chore(translations): updated white-paper.de.md

---

public/locales/de/layout.json

chore(translations): updated layout.json

---

cypress/integration/pages/developers.spec.ts
cypress/integration/pages/dex.spec.ts
cypress/integration/pages/dfi.spec.ts
cypress/integration/pages/learn.spec.ts
public/locales/de/page-index.json
public/locales/fr/page-index.json

The White Paper links on the index page for FR and DE was still pointing to the EN version. PR to update the links

`White Paper` Update white paper links on index page

---

public/locales/de/page-media.json

chore(translations): updated page-media.json

---

public/locales/de/page-index.json

chore(translations): updated page-index.json

---

public/locales/en-US/page-dfi.json
src/pages/dfi/_components/ERC20Section.tsx
src/pages/dfi/index.page.tsx

Add ERC20 content onto $DFI page

feat(erc20): Add ERC20 Section on DFI page

---

public/locales/en-US/page-dfi.json

chore(ERC20): Update ERC20 description

---

public/locales/de/layout.json
public/locales/en-US/layout.json
src/layouts/components/Header.tsx

Update header link to blog for DE to https://blog.defichain.com/de/

chore(headers): Update DE blog link

---

package-lock.json
package.json

Fixed dep error causing builds to fail

chore(deps): Fixed dep error

---

public/locales/de/page-downloads.json

fix: update DE desc

---

cypress/.eslintrc
cypress/e2e/layout/footer.spec.ts
src/layouts/components/Footer.tsx

feature(ui-ux): add portuguese and indonesia on Footer

---

cypress/e2e/layout/footer.spec.ts
public/locales/de/layout.json
public/locales/en-US/layout.json
public/locales/fr/layout.json
public/locales/zh-Hans/layout.json
public/locales/zh-Hant/layout.json
src/layouts/components/Footer.tsx

feature(ui-ux): added cmc to social link

---

package-lock.json
package.json

chore(deps): upgrade cypress to ^11.1.0

---

package-lock.json
package.json
src/pages/bug-bounty/_components/Hunter.tsx
src/pages/dex/_components/LiquidityPoolsSection.tsx

This PR updated the react-number-format library to the latest version

chore(deps): update react-number-format to v5

---

package.json
pnpm-lock.yaml

chore(deps): add ipx

---

.npmrc
package.json
pnpm-lock.yaml

chore(deps): updated configs

---

cypress.config.js
cypress/e2e/layout/footer.spec.ts
cypress/e2e/layout/header.spec.ts
cypress/e2e/pages/developers.spec.ts
cypress/e2e/pages/dex.spec.ts
cypress/e2e/pages/dfi.spec.ts
cypress/e2e/pages/downloads.spec.ts
cypress/e2e/pages/ecosystem.spec.ts
cypress/e2e/pages/index.spec.ts
cypress/e2e/pages/learn.spec.ts
cypress/e2e/pages/media.spec.ts
cypress/support/commands.ts
package.json
pnpm-lock.yaml

Cypress migration guide to v12 doc: https://docs.cypress.io/guides/references/migration-guide#Migrating-to-Cypress-120
Cypress V12 changelog: https://docs.cypress.io/guides/references/changelog#12-0-0

chore(deps): DW-43 update Cypress to v12

---

src/styles/globals.css
tailwind.config.js

As titled. 
This PR updates tailwindconfigs styling in preparation of 2.0

chore: update tailwindconfigs for 2.0

---

src/components/commons/Buttons.tsx
src/layouts/components/Header.tsx
src/styles/globals.css

As titled
Yet to remove `ButtonUnfilled` yet as to load main screen without error. To remove when start developing main screen

feat(ui-ux): add Buttons 2.0 component

---

public/locales/de/page-downloads.json
public/locales/fr/page-downloads.json

adding translations, standardization

chore(translations): updated de/page-downloads.json

---

src/components/commons/SectionTitle.tsx
src/components/index/ReadyForFlexibility.tsx
src/styles/globals.css
tailwind.config.js

As titled
addded common component for the below

feat(ui-ux): add common component SectionTitle

---

src/layouts/components/Header.tsx
src/layouts/components/HeaderNavLinkItem.tsx

as titled. Updated header hover and pressed state text colors based on updated dsm

fix(ui-ux): minor text color changes in header

---

.github/workflows/ci-e2e.yml
.github/workflows/ci.yml
.npmrc
package.json
pnpm-lock.yaml

chore(ops): bump pnpm

---

public/locales/zh-Hans/page-downloads.json
public/locales/zh-Hant/page-downloads.json

chore: add ZH translations for quantum

---

src/components/commons/Container.tsx
src/components/index/DeFiChainEcoSystemSection.tsx
src/components/index/ReadyForFlexibility.tsx

fix(ui-ux): standardize Container component

---

src/layouts/components/LanguageDropdownV2.tsx

- Handle hover state of language dropdown button

fix(ui-ux): language dropdown UI

---

.github/workflows/ci-e2e.yml
.github/workflows/ci.yml
package.json
pnpm-lock.yaml

chore(ops): update deps

---

public/locales/en-US/layout.json
src/components/commons/Buttons.tsx
src/components/index/HomePageHeader.tsx
src/layouts/components/Header.tsx
src/pages/explore/dex/_components/DexStatisticsDisplay.tsx
src/pages/explore/dfi/_components/DFIStatisticsDisplay.tsx
src/pages/explore/dfi/_components/GetDFISection.tsx
src/pages/explore/dfi/index.page.tsx

- As titled
- Fix homepage banner video blocking text on physical mobile device
- Remove description text for stat panel in `explore/dex`

feature(header): link get DFI button to `explore/dfi`

---

public/locales/en-US/layout.json
public/locales/en-US/page-explore-dex.json
public/locales/en-US/page-explore-dfi.json
public/locales/en-US/page-explore-masternodes.json
public/locales/en-US/page-explore-wallets.json
public/locales/en-US/page-index.json
src/components/commons/SectionGridLayout.tsx
src/pages/explore/dfi/_components/ERC20Section.tsx

- As titled
- Update secondary button UI

chore(copy): update home and explore pages

---

public/locales/de/layout.json
public/locales/de/page-index.json

- As titled
- TODO: jumpstart into defichain ecosystem section as there are content changes

chore(translation): add DE for homepage

---

src/components/commons/SectionTitle.tsx
src/components/commons/StatisticPanel.tsx
src/components/index/BlockchainFeatureColumn.tsx
src/components/index/DeFiChainEcoSystemSection.tsx
src/components/index/ReadyForFlexibility.tsx
src/components/index/RoadMapSection.tsx
src/components/index/blogPosts/BlogPostsSection.tsx
src/components/index/blogPosts/PostCard.tsx
src/components/index/components/Card.tsx
src/pages/explore/dfi/_components/ERC20Section.tsx
src/pages/explore/dfi/_components/GetDFISection.tsx
src/pages/explore/dfi/_components/GetDFISectionExchanges.tsx
src/pages/explore/dfi/_components/HarnessDFIGrid.tsx
src/pages/explore/dfi/_components/HarnessDFISection.tsx
src/pages/explore/dfi/_components/InitialTokenDistributionSection.tsx
src/pages/explore/masternodes/SvgIconsColumn.tsx
src/pages/explore/wallets/_components/CardLink.tsx
src/pages/explore/wallets/_components/ForDailyUseSection.tsx

- As titled, to improve accessibility and seo

chore(html): use semantic markup tags

---

public/locales/de/layout.json
public/locales/de/page-explore-dfi.json
public/locales/en-US/layout.json
public/locales/fr/layout.json
public/locales/fr/page-explore-dfi.json
public/locales/zh-Hans/layout.json
public/locales/zh-Hans/page-explore-dfi.json
public/locales/zh-Hant/layout.json
public/locales/zh-Hant/page-explore-dfi.json
src/components/commons/Buttons.tsx
src/components/index/DeFiChainEcoSystemSection.tsx

As titled. 
This PR also fixed the missing `de` translations on homepage ecosystem section
This PR also fixes secondary button to use border instead of outline for rounding of secondary buttons in mobile view

chore(ui-ux): update translations for explore/dfi and header

---

src/components/icons/assets/whyDex/TradeAssets.tsx
src/pages/explore/masternodes/MasternodesBenefitsSection.tsx
src/pages/explore/masternodes/SvgIconsColumn.tsx

- As titled, in `explore/dex` and `explore/masternodes` pages

fix(ui): icon placement in physical mobile device

---

src/pages/explore/dfi/_components/InitialTokenDistributionSection.tsx

add href link to white paper in explore dfi page

---

src/layouts/components/Build.tsx
src/layouts/components/Community.tsx
src/layouts/components/Ecosystem.tsx
src/layouts/components/Explore.tsx
src/layouts/components/HeaderNavLinkItem.tsx

chore(ui-ux): add testid

---

src/components/commons/Buttons.tsx
src/components/index/ReadyForFlexibility.tsx
src/components/index/blogPosts/BlogPostsSection.tsx

fix(ui-ux): update external link buttons in homepage

---

src/components/commons/SectionGridLayout.tsx

fix(ui): why dex button missing horizontal padding

---

public/assets/icon/CryptoIDIcon.tsx

fix(ui-ux): fix CryptoID not color changing in safari

---

src/components/index/BlockchainFeatureColumn.tsx

`w-fit` does not work accurately on Safari.

fix(ui-ux): ui fixes for safari

---

src/components/index/DeFiChainEcoSystemSection.tsx

fix(ui-ux): fix scroll issue in firefox

---

src/layouts/Default.tsx

chore: change to bigger twitter card

---

public/_redirects
public/locales/de/layout.json
public/locales/en-US/layout.json
public/locales/fr/layout.json
src/layouts/Default.tsx

- As titled
- Update link share card title, both open graph and twitter
- Update translations
- Add redirects

chore: update card title & translations & redirects

---

public/_redirects

fix: add https in redirect

---

public/_redirects

chore(redirects): redirect "/download" to "wallets"

---

public/locales/de/page-explore-wallets.json

Adding translation and translation  improvements

chore(translations): updated de/page-explore-wallets.json

---

.github/workflows/ci-e2e.yml
.github/workflows/ci.yml
README.md
netlify.toml
package.json
pnpm-lock.yaml
src/pages/bug-bounty/index.page.tsx
src/pages/learn/[slug].page.tsx
src/pages/learn/index.page.tsx
src/pages/privacy-policy.page.tsx
src/pages/security.page.tsx
src/pages/white-paper.page.tsx

chore(deps): update deps and corepack

---

src/pages/white-paper.page.tsx

fix(ui-ux): fix whitepaper scrolling bug

---

cypress/e2e/homepage.spec.ts
public/locales/de/page-index.json
public/locales/en-US/page-index.json
public/locales/fr/page-index.json
public/locales/zh-Hans/page-index.json
public/locales/zh-Hant/page-index.json
src/components/index/ReadyForFlexibility.tsx
src/layouts/components/HeaderNavLinkItem.tsx

feat(ui-ux): update MetaChain link and title on homepage

---

public/locales/de/page-meta-chain.json
public/locales/en-US/page-meta-chain.json
public/locales/fr/page-meta-chain.json
public/locales/zh-Hans/page-meta-chain.json
public/locales/zh-Hant/page-meta-chain.json

This PR changes the status of 2 items in the Meta-chain agenda, Testnet and Mainnet Launch is set to `Deployed` with green status.

chore(ui-ux): change metachain agenda status

---

public/locales/de/page-explore-wallets.json
public/locales/en-US/page-explore-wallets.json
public/locales/fr/page-explore-wallets.json
src/components/icons/assets/downloadAssets/BTCDFILogo.tsx
src/components/icons/assets/downloadAssets/DFI3D.tsx
src/pages/explore/wallets/_components/VisualAssetsSection.tsx

fix(ui-ux): visual assets card section

---

cypress/e2e/homepage.spec.ts
public/locales/de/page-index.json
src/components/commons/StatisticPanel.tsx
src/components/index/BlockchainFeaturesSection.tsx
src/components/index/HomePageHeader.tsx
src/components/index/StatisticsDisplay.tsx
src/hooks/useUnitSuffix.tsx

To fix de translations reported issues https://cakedefi.slack.com/archives/G01LP9ZHGS3/p1707471965499879

fix(ui-ux): de translations on landing page
